server:
  port: 11013
spring:
  application:
    name: zipkin-client-backendName
  zipkin:
    enabled: true
    # zipkin server地址，如果使用mq收集，这个就不要配置
#    base-url: http://localhost:9411
  # 应采样的请求百分比。例如1.0= 100％的请求应该被抽样。精度仅为全数（即不支持0.1％的痕迹）。开发过程使用1.0，生产根据实际情况设置
  sleuth:
    sampler:
      percentage: 1.0
 #rabbitmq\u914D\u7F6E
  rabbitmq:
    host: 127.0.0.1
    port : 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
        acknowledge-mode: auto